### ISSUE TITLE
Build error - Jessie Build Apu64 for PCEngines APU1D 

### ISSUE THREAD

**Issue by ghost** [ssinyagin/pcengines-apu-debian-cd#7]
Hi everyone, 

I was building the Jessie image for the PCEngines APU1D (mSata SSD 16GB) when some errors occurred : 

Traceback (most recent call last):
  File "/usr/bin/build-simple-cdd", line 637, in <module>
    scdd.build_mirror()
  File "/usr/bin/build-simple-cdd", line 261, in build_mirror
    self.run_tool("mirror", tool)
  File "/usr/bin/build-simple-cdd", line 358, in run_tool
    tool.run()
  File "/usr/lib/python3/dist-packages/simple_cdd/tools/mirror_reprepro.py", line 193, in run
    print_records("updates", "Name", field_order, updates_used, updates)
  File "/usr/lib/python3/dist-packages/simple_cdd/tools/mirror_reprepro.py", line 184, in print_records
    print("{}: {}".format(field, self.env.format(val, verify_release_keys=verify_release_keys)), file=fd)
  File "/usr/lib/python3/dist-packages/simple_cdd/env.py", line 390, in format
    return string.format(_args, *_kwargs)
KeyError: 'security_mirro'

I did it on a Debian 8 Build-machine, have you any ideas on how I can solve it ?

**Comment by ghost** [comment]
I solved by analizing python files. The error can be found in /usr/lib/python3/dist-packages/simple_cdd/tools/mirror_reprepro.py:78. The error is {security_mirro}r. The correct is {security_mirror}
